name: airline_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.8+8

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade y    our package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # mapbox_maps_flutter: ^2.0.0 # Ensure this is correctly formatted
  # Add other dependencies here

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  build_runner: ^2.4.13
  carousel_slider: ^5.0.0
  button_animations: ^2.0.0+3
  syncfusion_flutter_datepicker: ^31.1.23
  latlong2: ^0.9.1
  http: ^1.2.2
  file_picker: ^10.3.3
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  loading_indicator: ^3.1.1
  permission_handler: ^12.0.1
  google_sign_in: ^7.2.0
  otpless_flutter: ^2.2.1
  web_socket_channel: ^3.0.1
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_emoji_feedback: ^1.0.3
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  mobile_scanner: ^7.1.2
  country_flags: ^4.0.1
  country_codes: ^3.1.0+2
  sealed_countries: ^2.7.0
  gif: ^2.3.0
  dio: ^5.7.0
  fl_chart: ^1.1.1
  geocoding: ^4.0.0
  csv: ^6.0.0
  google_mlkit_text_recognition: ^0.15.0
  googleapis: ^15.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  video_player: ^2.9.2
  flutter_svg: ^2.0.16
  google_mlkit_barcode_scanning: ^0.14.1
  url_launcher: ^6.3.1
  share_plus: ^12.0.0
  googleapis_auth: ^2.0.0
  flutter_launcher_icons: "^0.14.2"
  http_parser: ^4.0.2
  mime: ^2.0.0
  animated_flip_counter: ^0.3.4
  # aws_s3_api: ^2.0.0  # Temporarily disabled due to dependency conflicts
  convex_bottom_bar: ^3.2.0
  shimmer: ^3.0.0
  path: ^1.9.0
  flutter_local_notifications: ^19.0.2
  workmanager: ^0.5.2
  supabase_flutter: ^2.10.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/logoIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff" # or any color you prefer
  adaptive_icon_foreground: "assets/icon/logoIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/icon/
  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro
      fonts:
        - asset: fonts/SF-Pro-Display-Black.otf
        - asset: fonts/SF-Pro-Display-BlackItalic.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
        - asset: fonts/SF-Pro-Display-BoldItalic.otf
        - asset: fonts/SF-Pro-Display-Heavy.otf
        - asset: fonts/SF-Pro-Display-HeavyItalic.otf
        - asset: fonts/SF-Pro-Display-Light.otf
        - asset: fonts/SF-Pro-Display-LightItalic.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
        - asset: fonts/SF-Pro-Display-MediumItalic.otf
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-RegularItalic.otf
        - asset: fonts/SF-Pro-Display-Semibold.otf
        - asset: fonts/SF-Pro-Display-SemiboldItalic.otf
        - asset: fonts/SF-Pro-Display-Thin.otf
        - asset: fonts/SF-Pro-Display-ThinItalic.otf
        - asset: fonts/SF-Pro-Display-Ultralight.otf
        - asset: fonts/SF-Pro-Display-UltralightItalic.otf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package